### ISSUE TITLE
can't convert nil into String

### ISSUE THREAD

**Issue by falconsapsan** [prey/prey-standalone-control-panel#4]
After entering the login / password, I get an error

can't convert nil into String
file: admin.rb location: + line: 34

ruby 1.9.3p484 (2013-11-22 revision 43786) [x86_64-linux]
Rack 1.3 (Release: 1.6.4)

**Comment by hippich** [comment]
I just got same problem and was able to get around it using a bit older version of `bowtie` gem. In `Gemfile` make this change:

```
-gem 'bowtie'
+gem 'bowtie', '0.5.2'
```

**Comment by todx2** [comment]
Yep, I was having the same problem here and  solved it by downgrading bowtie like hippich did

**Comment by michelson** [comment]
thanks for report this! @hippich @falconsapsan @todx2 ! 🎉

**Comment by 15w34r0n3D4y** [comment]
Hey, i get this error too and then install gem bowtie v 0.5.2, but now i get error:

Mongo::ConnectionFailure at /admin/devices 

Failed to connect to a master node at localhost:27017

    file: mongo_client.rb location: connect line: 417 

How fix it, thank you for help.
